services:
  backend:
    build:
      context: ./backend
    container_name: mapapp-be
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    container_name: mapapp-fe
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped
